vfoss_src/vfoss_org/old_addons/djangocms-blog/djangocms_blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .feeds import LatestEntriesFeed, TagFeed
from .views import (AuthorEntriesView, CategoryEntriesView, PostArchiveView, PostDetailView,
                    PostListView, TaggedListView)

urlpatterns = patterns(
    '',
    url(r'^$', PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$', LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^(?P<year>\d{4})/$', PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$', PostDetailView.as_view(), name='post-detail'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$', AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$', CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$', TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$', TagFeed(), name='posts-tagged-feed'),
)

vfoss_src/vfoss_org/vfoss_news/urls.py
from django.urls import include, path
from vfoss_news import views

urlpatterns = [
        path(r'^$', views.index, name='index'),
        #url(r'^(?P<category_slug>[-\w]+)/$', views.index, name='index'),
        ]

vfoss_src/vfoss_org/vfoss_org/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

from django.contrib.auth import views as auth_views

#admin.autodiscover() # Not required for Django 1.7.x+

urlpatterns = i18n_patterns(
    path(r'admin/', admin.site.urls),

    ## python-social-auth
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    #path('', include('django.contrib.auth.urls')),
    #path('social/', include('social.apps.django_app.urls')),
    path('social/', include(('social_django.urls', 'social'), namespace='social')),

    ##
    #path('password_reset_done/', auth_views.password_reset_done, name='password_reset_done'),
    #path('password_change_done/', auth_views.password_change_done, name='password_change_done'),
    #override the default urls
    #path(r'^password/change/$',
    #    auth_views.password_change,
    #    name='password_change'),
    #path(r'^password/change/done/$',
    #    auth_views.password_change_done,
    #    name='password_change_done'),
    #path(r'^password/reset/$',
    #    auth_views.password_reset,
    #    name='password_reset'),
    #path(r'^password/reset/done/$',
    #    auth_views.password_reset_done,
    #    name='password_reset_done'),
    #path(r'^password/reset/complete/$',
    #    auth_views.password_reset_complete,
    #    name='password_reset_complete'),
    #path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #    auth_views.password_reset_confirm,
    #    name='password_reset_confirm'),

    ## djangocms-blog
    path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),

    ## vfoss-news
#    path(r'^news/', include('vfoss_news.urls')),

    ## django-cms
    path(r'', include('cms.urls')),
    # hide default language code abc.com/en/ --> abc.com
    prefix_default_language=False
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#from django.contrib.auth import views as auth_views
#urlpatterns += [
#    path(r'^change-password/$', 'django.contrib.auth.views.password_change', name="password-change")
#]

#urlpatterns += [
#		# misago
#		path(r'forums^', include('misago.urls')),
#		]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
            path(r'^__debug__/', include(debug_toolbar.urls)),
            ]

vfoss_src/vfoss_org/old_addons/djangocms-blog/djangocms_blog/models.py
# -*- coding: utf-8 -*-
from cms.models import CMSPlugin, PlaceholderField
from django.conf import settings as dj_settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import force_text, python_2_unicode_compatible
from django.utils.html import escape, strip_tags
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language
from djangocms_text_ckeditor.fields import HTMLField
from filer.fields.image import FilerImageField
from meta_mixin.models import ModelMeta
from parler.managers import TranslationManager
from parler.models import TranslatableModel, TranslatedFields
from taggit_autosuggest.managers import TaggableManager

from .managers import GenericDateTaggedManager
from .settings import get_setting

BLOG_CURRENT_POST_IDENTIFIER = 'djangocms_post_current'


@python_2_unicode_compatible
class BlogCategory(TranslatableModel):
    """
    Blog category
    """
    parent = models.ForeignKey('self', verbose_name=_('parent'), null=True,
                               blank=True)
    date_created = models.DateTimeField(_('created at'), auto_now_add=True)
    date_modified = models.DateTimeField(_('modified at'), auto_now=True)

    translations = TranslatedFields(
        name=models.CharField(_('name'), max_length=255),
        slug=models.SlugField(_('slug'), blank=True, db_index=True),
        meta={'unique_together': (('language_code', 'slug'),)}
    )

    objects = TranslationManager()

    class Meta:
        verbose_name = _('blog category')
        verbose_name_plural = _('blog categories')

    @property
    def count(self):
        return self.blog_posts.published().count()

    def get_absolute_url(self):
        lang = get_language()
        if self.has_translation(lang):
            slug = self.safe_translation_getter('slug', language_code=lang)
            return reverse('djangocms_blog:posts-category', kwargs={'category': slug})
        # in case category doesn't exist in this language, gracefully fallback
        # to posts-latest
        return reverse('djangocms_blog:posts-latest')

    def __str__(self):
        return self.safe_translation_getter('name')

    def save(self, *args, **kwargs):
        super(BlogCategory, self).save(*args, **kwargs)
        for lang in self.get_available_languages():
            self.set_current_language(lang)
            if not self.slug and self.name:
                self.slug = slugify(force_text(self.name))
        self.save_translations()


@python_2_unicode_compatible
class Post(ModelMeta, TranslatableModel):
    """
    Blog post
    """
    author = models.ForeignKey(dj_settings.AUTH_USER_MODEL,
                               verbose_name=_(u'author'), null=True, blank=True,
                               related_name='djangocms_blog_post_author')

    date_created = models.DateTimeField(_(u'created'), auto_now_add=True)
    date_modified = models.DateTimeField(_(u'last modified'), auto_now=True)
    date_published = models.DateTimeField(_(u'published Since'),
                                          default=timezone.now)
    date_published_end = models.DateTimeField(_(u'published Until'), null=True,
                                              blank=True)
    publish = models.BooleanField(_(u'publish'), default=False)
    categories = models.ManyToManyField('djangocms_blog.BlogCategory', verbose_name=_(u'category'),
                                        related_name='blog_posts',)
    main_image = FilerImageField(verbose_name=_(u'main image'), blank=True, null=True,
                                 on_delete=models.SET_NULL,
                                 related_name='djangocms_blog_post_image')
    main_image_thumbnail = models.ForeignKey('cmsplugin_filer_image.ThumbnailOption',
                                             verbose_name=_(u'main image thumbnail'),
                                             related_name='djangocms_blog_post_thumbnail',
                                             on_delete=models.SET_NULL,
                                             blank=True, null=True)
    main_image_full = models.ForeignKey('cmsplugin_filer_image.ThumbnailOption',
                                        verbose_name=_(u'main image full'),
                                        related_name='djangocms_blog_post_full',
                                        on_delete=models.SET_NULL,
                                        blank=True, null=True)
    enable_comments = models.BooleanField(verbose_name=_(u'enable comments on post'),
                                          default=get_setting('ENABLE_COMMENTS'))
    sites = models.ManyToManyField('sites.Site', verbose_name=_(u'Site(s)'), blank=True,
                                   null=True,
                                   help_text=_(u'Select sites in which to show the post. '
                                               u'If none is set it will be '
                                               u'visible in all the configured sites.'))

    translations = TranslatedFields(
        title=models.CharField(_(u'title'), max_length=255),
        slug=models.SlugField(_(u'slug'), blank=True, db_index=True),
        abstract=HTMLField(_(u'abstract'), blank=True, default=''),
        meta_description=models.TextField(verbose_name=_(u'post meta description'),
                                          blank=True, default=''),
        meta_keywords=models.TextField(verbose_name=_(u'post meta keywords'),
                                       blank=True, default=''),
        meta_title=models.CharField(verbose_name=_(u'post meta title'),
                                    help_text=_(u'used in title tag and social sharing'),
                                    max_length=255,
                                    blank=True, default=''),
        post_text=HTMLField(_(u'text'), default='', blank=True),
        meta={'unique_together': (('language_code', 'slug'),)}
    )
    content = PlaceholderField('post_content', related_name='post_content')

    objects = GenericDateTaggedManager()
    tags = TaggableManager(blank=True, related_name='djangocms_blog_tags')

    _metadata = {
        'title': 'get_title',
        'description': 'get_description',
        'og_description': 'get_description',
        'twitter_description': 'get_description',
        'gplus_description': 'get_description',
        'keywords': 'get_keywords',
        'locale': None,
        'image': 'get_image_full_url',
        'object_type': get_setting('TYPE'),
        'og_type': get_setting('FB_TYPE'),
        'og_app_id': get_setting('FB_APPID'),
        'og_profile_id': get_setting('FB_PROFILE_ID'),
        'og_publisher': get_setting('FB_PUBLISHER'),
        'og_author_url': get_setting('FB_AUTHOR_URL'),
        'twitter_type': get_setting('TWITTER_TYPE'),
        'twitter_site': get_setting('TWITTER_SITE'),
        'twitter_author': get_setting('TWITTER_AUTHOR'),
        'gplus_type': get_setting('GPLUS_TYPE'),
        'gplus_author': get_setting('GPLUS_AUTHOR'),
        'published_time': 'date_published',
        'modified_time': 'date_modified',
        'expiration_time': 'date_published_end',
        'tag': 'get_tags',
        'url': 'get_absolute_url',
    }

    class Meta:
        verbose_name = _('blog article')
        verbose_name_plural = _('blog articles')
        ordering = ('-date_published', '-date_created')
        get_latest_by = 'date_published'

    def __str__(self):
        return self.safe_translation_getter('title')

    def get_absolute_url(self):
        kwargs = {'year': self.date_published.year,
                  'month': '%02d' % self.date_published.month,
                  'day': '%02d' % self.date_published.day,
                  'slug': self.safe_translation_getter('slug',
                                                       language_code=get_language(),
                                                       any_language=True)}
        return reverse('djangocms_blog:post-detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
        main_lang = self.get_current_language()
        for lang in self.get_available_languages():
            self.set_current_language(lang)
            if not self.slug and self.title:
                self.slug = slugify(self.title)
        self.set_current_language(main_lang)
        self.save_translations()

    def get_title(self):
        title = self.safe_translation_getter('meta_title', any_language=True)
        if not title:
            title = self.safe_translation_getter('title', any_language=True)
        return title.strip()

    def get_keywords(self):
        return self.safe_translation_getter('meta_keywords').strip().split(',')

    def get_description(self):
        description = self.safe_translation_getter('meta_description', any_language=True)
        if not description:
            description = self.safe_translation_getter('abstract', any_language=True)
        return escape(strip_tags(description)).strip()

    def get_image_full_url(self):
        if self.main_image:
            return self.make_full_url(self.main_image.url)
        return ''

    def get_tags(self):
        taglist = [tag.name for tag in self.tags.all()]
        return ','.join(taglist)

    def get_author(self):
        return self.author

    def thumbnail_options(self):
        if self.main_image_thumbnail_id:
            return self.main_image_thumbnail.as_dict
        else:
            return get_setting('IMAGE_THUMBNAIL_SIZE')

    def full_image_options(self):
        if self.main_image_full_id:
            return self.main_image_full.as_dict
        else:
            return get_setting('IMAGE_FULL_SIZE')

    def get_full_url(self):
        return self.make_full_url(self.get_absolute_url())


@python_2_unicode_compatible

vfoss_src/vfoss_org/vfoss_org/templates/djangocms_blog_orig/base.html
{#CMS_TEMPLATE is a context variable available in the context; it contains the template path for CMS pages and application using apphooks, and the default template (i.e.: the first template in CMS_TEMPLATES) for non-CMS managed URLs.#}

{% extends CMS_TEMPLATE %}
{#% extends "vfoss_org/base.html" %#}
{% load cms_tags menu_tags %}

{% block main_content %}


{% block meta %}
    {%  if meta %}
        {% include "meta_mixin/meta.html" %}
    {% endif %}
{% endblock meta %}

{% block content %}
<div class="app app-blog">
    {% block content_blog %}{% endblock %}
</div>
{% endblock content %}

{% endblock main_content%}

{# ------------------------------------------------------------ #}
{% block sidebar_cross_app_1 %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Most Shared Sources</h3>
  </div>
  <div class="panel-body">
		{# static_placeholder allow adding plugins like authors, latest articles, etc #}
		{# to site structure #}
		{% static_placeholder "most_shared_sources" %}
  </div>
</div>
{% endblock sidebar_cross_app_1 %}
{# ------------------------------------------------------------ #}

{# ------------------------------------------------------------ #}
{% block sidebar_cross_app_2 %}
{% endblock sidebar_cross_app_2 %}
{# ------------------------------------------------------------ #}

{# ------------------------------------------------------------ #}
{% block sidebar_tab_panel %}
<div class="panel panel-default">
	<div class="panel-heading">
		<!-- Nav tabs -->
		<ul class="nav nav-pills">
			<li><a href="#comments" data-toggle="tab">Comments</a></li>
			<li><a href="#authors" data-toggle="tab">Authors</a></li>
			<li><a href="#archives" data-toggle="tab">Archives</a></li>
		</ul>
	</div>
	<div class="panel-body">
		<div class="tab-content">
			<div class="tab-pane fade in active" id="comments">
				{% static_placeholder "blog_plugin_comments" %}
			</div>
			<div class="tab-pane fade" id="authors">
				{# blog_show_authors #}
				{% static_placeholder "blog_plugin_authors" %}
			</div>
			<div class="tab-pane fade" id="archives">
				{% static_placeholder "blog_plugin_archives" %}
			</div>
		</div>

	</div>
</div>
{% endblock sidebar_tab_panel %}
{# ------------------------------------------------------------ #}

{# ------------------------------------------------------------ #}
{% block sidebar_sample_panel %}
{% endblock sidebar_sample_panel %}

vfoss_src/vfoss_org/vfoss_org/templates/djangocms_blog_orig/post_archive.html
{% extends "djangocms_blog/post_list.html" %}

vfoss_src/vfoss_org/vfoss_org/templates/djangocms_blog_orig/post_detail.html
{% extends "djangocms_blog/base.html" %}
{% load i18n thumbnail cms_tags %}

{% block meta_description %}{{ post.meta_description }}{% endblock meta_description %}
{% block meta_keywords %}{{ post.meta_keywords }}{% endblock meta_keywords %}
{% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
{% block title %}{{ post.get_title }}{% endblock %}

{% block content_blog %}{% spaceless %}
<article id="post-{{ post.slug }}" class="post-item post-detail">
    <header>
        <h2>{% render_model post "title" %}</h2>
        {% block blog_meta %}
            {% include "djangocms_blog/includes/blog_meta.html" %}
        {% endblock %}
    </header>
    {% if post.main_image_id %}
    <div class="blog-visual">
        {% thumbnail post.main_image post.full_image_options.size crop=post.full_image_options.crop upscale=post.full_image_options.upscale subject_location=post.main_image.subject_location  as thumb %}
        <img src="{{ thumb.url }}" alt="{{ post.main_image.default_alt_text }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />
    </div>
    {% endif %}
    {% endspaceless %}
    {% if post.app_config.use_placeholder %}
        <div class="blog-content">{% render_placeholder post.content %}</div>
    {% else %}
        <div class="blog-content">{% render_model post "post_text" "post_text" "" "safe" %}</div>
    {% endif %}
</article>
{% endblock content_blog %}

vfoss_src/vfoss_org/vfoss_org/templates/djangocms_blog_orig/post_instant_article.html
{% load thumbnail cms_tags %}
<!doctype html>
<html lang="{{ post.get_current_language }}" prefix="op: http://media.facebook.com/op#">
  <head>
    <meta charset="utf-8">
    {% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
    <meta property="op:markup_version" content="v1.0">
  </head>
  <body>
    <article>
      <header>
        <h1>{{ post.title }}</h1>
        <time class="op-published" datetime="{{ post.date_published|date:"Y-m-d\TH:i:sO" }}">{{ post.date_published|date:"DATE_FORMAT" }}</time>
        <time class="op-modified" dateTime="{{ post.date_modified|date:"Y-m-d\TH:i:sO" }}">{{ post.date_modified|date:"DATE_FORMAT" }}</time>
        <address>
            <a {% if og_author_url %}rel="facebook" href="{{ og_author_url }}"{% endif %}>{{ post.get_author_name }}</a>
        </address>
        <figure>
            <img src="{{ meta.image }}" alt="{{ post.main_image.default_alt_text|default:'' }}" />
            {% if post.main_image.default_caption %}<figcaption>{{ post.main_image.default_caption }}</figcaption>{% endif %}
        </figure>
        <h3 class="op-kicker">{{ post.abstract|striptags|safe }}</h3>
      </header>
      {% if post.app_config.use_placeholder %}
      <div class="blog-content">{% render_placeholder post.content %}</div>
      {% else %}
      <div class="blog-content">{% render_model post "post_text" "post_text" "" "safe" %}</div>
      {% endif %}
    </article>
  </body>
</html>

vfoss_src/vfoss_org/vfoss_org/templates/djangocms_blog_orig/post_list.html
{% extends "djangocms_blog/base.html" %}
{% load i18n thumbnail %}{% spaceless %}

{% block canonical_url %}<link rel="canonical" href="{{ view.get_view_url }}"/>{% endblock canonical_url %}

{% block content_blog %}
<section class="blog-list">
    {% block blog_title %}
    <header>
        <h2>
        {% if author %}{% trans "Articles by" %} {{ author.get_full_name }}
        {% elif archive_date %}{% trans "Archive" %} &ndash; {% if month %}{{ archive_date|date:'F' }} {% endif %}{{ year }}
        {% elif tagged_entries %}{% trans "Tag" %} &ndash; {{ tagged_entries|capfirst }}
        {% elif category %}{% trans "Category" %} &ndash; {{ category }}{% endif %}
        </h2>
    </header>
    {% endblock %}
    {% for post in post_list %}
        {% include "djangocms_blog/includes/blog_item.html" with post=post image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
    {% empty %}
    <p class="blog-empty">{% trans "No article found." %}</p>
    {% endfor %}
    {% if author or archive_date or tagged_entries %}
    <p class="blog-back"><a href="{% url 'djangocms_blog:posts-latest' %}">{% trans "Back" %}</a></p>
    {% endif %}
    {% if is_paginated %}
    <nav class="{% firstof css_grid instance.css_grid %} pagination">
        {% if page_obj.has_previous %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
        {% endif %}
        <span class="current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
        {% endif %}
    </nav>
    {% endif %}
</section>
{% endblock %}
{% endspaceless %}